# Generated by Django 5.1 on 2024-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_alter_visitor_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
