# Generated by Django 5.1 on 2024-08-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_alter_visitor_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_data',
            name='ss_captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitor_data',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
