# Generated by Django 5.1 on 2024-08-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_visitor_data_ss_captured_alter_visitor_data_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor_data',
            name='ss_captured',
        ),
    ]
