# Generated by Django 5.1 on 2024-08-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_alter_visitor_data_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor_data',
            name='image',
        ),
    ]
