# Generated by Django 5.1 on 2024-08-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_remove_visitor_data_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor_data',
            name='created_at',
        ),
    ]
