# Generated by Django 5.1 on 2024-08-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_remove_visitor_data_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor_data',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
