# Generated by Django 5.1 on 2024-12-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_alter_visitor_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor_data',
            name='phone_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
